# Generated by Django 4.1 on 2024-05-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
