# Generated by Django 4.1 on 2024-05-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0004_emailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='email_host_user',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
